---
name: PEXProtection
author: RevivalPMMP
api: [1.0.0]
main: RevivalPMMP\PEXProtection\Main
version: 0.1.0

commands:
    pexprotection:
        description: PEXProtection command
        usage: /pexprotection <add/del>
        aliases: [pexp]
        permission: pexprotection.command
        
permissions:
    pexprotection.command:
        default: op
        description: Permission to use all PexProtection commands
...
